### ISSUE TITLE
TypeError: Cannot read property 'some' of undefined

### ISSUE THREAD

**Issue by MatissJanis** [Riron/effects-mapper#1]
```
ERROR ! TypeError: Cannot read property 'some' of undefined
    at /Users/xxx/effects-mapper/dist/tree-maker.js:6:29
    at Array.filter (<anonymous>)
    at getActionMap (/Users/xxx/effects-mapper/dist/tree-maker.js:5:28)
    at getEffectTree (/Users/xxx/effects-mapper/dist/tree-maker.js:29:19)
    at /Users/xxx/effects-mapper/dist/tree-maker.js:53:63
    at Array.map (<anonymous>)
    at Object.getEffectsTrees (/Users/xxx/effects-mapper/dist/tree-maker.js:53:32)
    at /Users/xxx/effects-mapper/dist/orchestrator.js:12:29```

**Comment by pringelmann** [comment]
+1 getting same error

**Comment by paskip** [comment]
Same here, any chance for update on this ?
